// InvoiceGeneration DTOs
import { Type } from 'class-transformer';
import { IsNotEmpty, IsNumber, IsPositive, IsString } from 'class-validator';

export class PostApiInvoicesRequestDto {
  // Order ids are generated by Prisma (cuid by default), so accept any non-empty id string.
  @IsString()
  @IsNotEmpty()
  orderId!: string;

  @Type(() => Number)
  @IsNumber({ maxDecimalPlaces: 2 })
  @IsPositive()
  amount!: number;
}

export interface PostApiInvoicesResponseDto {
  id: string;
  orderId: string;
  amount: number;
}

export interface GetApiInvoicesIdDownloadResponseDto {
  id: string;
  downloadUrl: string;
}
